apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: allocation-manager
 namespace: offender-management-staging
 annotations:
   kubernetes.io/ingress.class: “nginx”
spec:
  rules:
  - host: allocation-manager-staging.apps.cloud-platform-live-0.k8s.integration.dsd.io
    http:
      paths:
      - path: /
        backend:
          serviceName: allocation-manager
          servicePort: http
