apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: allocation-manager
 namespace: offender-management-production
 annotations:
   kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - allocation-manager-production.apps.cloud-platform-live-0.k8s.integration.dsd.io
  rules:
  - host: allocation-manager-production.apps.cloud-platform-live-0.k8s.integration.dsd.io
    http:
      paths:
      - path: /
        backend:
          serviceName: allocation-manager
          servicePort: 3000
