apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-environment
data:
  PROMETHEUS_METRICS: "on"
  DELIUS_EMAIL_FOLDER: "Data/prod"
  RAILS_ENV: "production"
  RAILS_SERVE_STATIC_FILES: "true"
  RAILS_WEB_CONCURRENCY: "5"
  PRISON_API_HOST: "https://api.prison.service.justice.gov.uk"
  NOMIS_OAUTH_HOST: "https://sign-in.hmpps.service.justice.gov.uk"
  NOMIS_OAUTH_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwSkdtYWp6SW9POVdSY2owM2VTbQpFeWJTYnNJaEdkNkRWVDRxUWFSRTZwN3RIN1ppSklvRWtzczRkOFphMGhuYWJwa0JqWTYwS3NnMW5teXpoZVlSCithWXVtc0gxbm1JcmJ4ZCtqV043T3A2V1pteWRBU3JMek1XWVdBYlNHOHBXMXkxY1RwdkRaMTlBSGJTYTRRL2UKSnRlcDFscCsyMnVHMW5kTVRwclRkNjRLTkcyZnRwcmV3aFExeE5xdmtUWjZoQnVRRVJKMzFhUXBkRThNQTFxSwpDWnI3VDJxTk1BTWNkTlpia0FqRjVLOXE0alZ0QkY3WXFPeXJ0T1JmTldqYUJoWHA5TlN0YWJCTXBURTdQNm8vClhJaU9rcmltNjlzaG1OdDhVRlU3WUlJN0ZvejgzM29HZnk2dmtDRjRxcGpIZ0RNc21STjc1UXRrRmRtaU8xaDgKcHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg"
  ZENDESK_USERNAME: "moic+zendesk@digital.justice.gov.uk"
  ZENDESK_URL: "https://ministryofjustice.zendesk.com/api/v2"
  LD_PRELOAD: "/usr/lib/x86_64-linux-gnu/libjemalloc.so.1"


