# Any environment not explicitly listed will default to false,
# except local and test, where the default will be true
#
feature_flags:
  example_feature:
    staging: true
  flatten_allocation_versions:
    staging: true
    preprod: true
